version: "3.9"

services:
  llm-gemini:
    image: lmaofrankie96/llm-gemini:latest
    ports:
      - "8001:8001"
    env_file:
      - ./variables.env

  orchestrator-api:
    image: lmaofrankie96/orchestrator-api:latest
    env_file:
      - ./variables.env
    environment:
      - LLM_API_URL=http://llm-gemini:8001/analyze_combined
    ports:
      - "8000:8000"
    depends_on:
      - llm-gemini

  dq-dashboard:
    image: lmaofrankie96/dq-dashboard:latest
    env_file:
      - ./variables.env
    ports:
      - "8501:8501"
    depends_on:
      - orchestrator-api
